### ISSUE TITLE
Computer and Robot doesn't work, get bootup error

### ISSUE THREAD

**Issue by ApolloX939** [loosewheel/lwcomputers#4]
![screenshot_20220505_165602](https://user-images.githubusercontent.com/20930999/167024197-01fc4158-418b-479f-9d5d-fe0277984f2d.png)

I obtained the computer and the 3 floppies from `/giveme` commands. (Not sure if that's affecting it or not)

## Versions

* Minetest: 5.5.0
* lwcomputers: [88f793e](https://github.com/loosewheel/lwcomputers/commit/88f793e07064a7d970e33f30834133d1185e4ef9)

> lwcomponents and lwscratch is installed too. (lwscratch robots work fine, it's lwcomputers computers and robots that don't work)

## What I've done to try and fix this

* I've added lwcomputers to secure.trusted_mods
* I've gave myself the items multiple times
* I've used lwcomputers trash to dispose of the previous items
* I've looked in minetest logs but it appears that isn't logged into minetest log. (Might want to have errors logged into minetest log so server admins can debug/troubleshoot)
* I've tried booting with just the LUA floppy and still get this error
* I've tried booting with just the LOS floppy and still get this error

**Comment by loosewheel** [comment]
I tried this with Minetest 5.5.0/MTG with just lwcomputers enabled and I'm not getting this error. This error is coming from the lua interpreter, so something else in your install might be involved. Can you detail what game you're using, the enabled mods and whether your version of Minetest is compiled with LuaJIT or standard Lua.

**Comment by ApolloX939** [comment]
Game: Minetest Game (edd033b708488472c6bd688b14d8a5f59ef5b218)
My minetest is compiled with standard Lua.

Mods list will be long, but here it is: (All these mods are enabled)
* 3d_armor
* drawers
* medblocks
* playeranim
* 3d_armor_mobile
* emoji
* mesecons
* playerlist
* adv_lightsabers
* enderpearl
* mesecons_window
* pontoons
* advtrains
* envelopes
* mesecons_wireless
* powerbanks
* afkkick
* ethereal
* minecart
* protector
* airtanks
* fancy_vend
* minetest-better_nametags
* renewPack
* airutils
* farming
* minetest_hbarmor
* resource_crops
* ambient_light
* feather-fall
* minetest_hbhunger
* roads
* anti_mobs (This is a custom mod I developed, so it can't be obtained by normal means, if you need a copy I can put it here, but for now it's a in house mod)
* filter
* minetest_hudbars
* ropes
* anti_unknown (Another custom mod I developed, again if you need a copy I can provide you one)
* fire_plus
* minetest_mod_weather
* scaffolding
* anvil
* floating_anchor
* minetest-toolranks
* schemedit
* area_containers
* frame
* minetest-toolranks-extras
* server_news
* automobiles_pck
* gauges
* Minetest-WorldEdit
* shifter_tool
* awards
* Gemstones
* mob_horse
* signs_lib
* basic_materials
* hazmat_suit
* mobkit
* skinsdb
* basic_trains
* hbsprint
* mobs_animal
* smartfs
* Biofuel
* helicopter
* mobs_monster
* smartshop
* bonemeal
* hidroplane
* mobs_npc
* spawn_point (Yet another custom mod I made, again if you need to look at it I can provide a copy)
* bouncy_bed
* home_point (Another custom mod I made, again copy can be provided)
* mobs_redo
* stasis
* bows
* hopper
* mobs_water
* supercub
* chat3
* intllib
* mod-atm
* technic
* inventorybags
* moreblocks
* technic_hv_extend
* climb_glove
* item_drop
* moreinfo
* teleporter_tool
* cloaking
* item_repair
* MoreMesecons
* travelnet
* controls
* item_replicator
* moreores
* unifieddyes
* creativefuel
* knockout
* more_up_packs
* unified_inventory
* ctf_guns
* lucky_block
* motorboat
* upgrade_packs
* currency
* **_lwcomponents_**
* nautilus
* visible_sneak
* digilines
* **_lwcomputers_**
* nether
* void_chest
* digistuff
* **_lwscratch_**
* obsidianstuff
* voltic_battery (Not on contentDB, see my github repo for a copy of it, need to release onto ContentDB, just lazy)
* digtron
* mail
* pa28
* wield3d
* display_modpack
* mailbox
* pipeworks
* wielded_light

> I hope I didn't miss anything :P

Yup, lots of mods were installed, I haven't tried localizing the issue, just occurred on my server thus decided to report it.

I highlighted and italicized your mods so you can see what mods you developed that I have running.

**Comment by loosewheel** [comment]
The error is occurring because the computer's sandboxed code is being called through pcall. The call through pcall is necessary to trap any error in the in game code and stop the error propagating up to the game engine and causing a crash. Apparently LuaJIT can do this but standard Lua can't. I can possibly push the call to pcall up the call stack and hopefully get code that will run with both LuaJIT and standard Lua, but this isn't just a tweek. It will take some time to do, and I'm not sure it can be done. If your in game code called pcall which then called os.sleep () this error may still occur and may be outside of the mod code to handle.

If you want to get it running, using Minetest compiled with LuaJIT will avoid this error. Until this works with standard Lua I'll make a note on the forum and contentdb that LuaJIT is required.

**Comment by ApolloX939** [comment]
Ah, ok, well I guess I have 2 options, disable a cool mod or try updating my docker image so it compiles with LuaJIT.

> For starters I think I will just disable the nice mod, to my sadness for now... then later on I will update my building so it has LuaJIT in it to go along with the custom Irlich that minetest 5.5.0 requires. (Hey at least I now know what's happening)

**Comment by ApolloX939** [comment]
> I  guess this issue can be closed then, since the issue is some what resolved.

**Comment by ApolloX939** [comment]
Oh I even tried fixing this by adding lwcomputers to secured.trusted_mods.

> But obviously it sounds like it's a using standard Lua rather than using LuaJIT.

**Comment by loosewheel** [comment]
Unfortunately no quick fix or work around. Its going to take a bit of re-coding and a lot testing, and until I do it I'm not sure that I can get it to even work.

And yes, adding lwcomputers to trusted mods only enables the http interface, which is disable by Minetest for mods by default. It won't do anything with regards to this issue.

My install comes from a repository, precompiled with LuaJIT. While I have compiled a few version of Minetest locally for mod testing and development, I can't say they have been tested with standard Lua. This error occurred as soon as LOS entered it's main loop. This doesn't do much testing for compatibility. If there are functional differences between standard Lua and LuaJIT, this may not be the only problem.
